[package]
name = "rsdkv6-extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.33.0"
md5 = "0.7.0"
dunce = "1.0.4"
json = "0.12.4"
